### ISSUE TITLE
Some model variants failed to save the rds file

### ISSUE THREAD

**Issue by elgabbas** [aniskhan25/hmsc-hpc#16]
Hello,

I am running some models using Hmsc-HPC. Some of the models worked as expected while others were not able to save the RDS files. These models save large temp files but fail to compress/convert them into RDS format.

![TempFile](https://github.com/aniskhan25/hmsc-hpc/assets/7375051/6213b5fd-e9dc-4b81-b1ad-b91b8389c311)

Here is an example error message I receive

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "****/hmsc-hpc/hmsc/run_gibbs_sampler.py", line 227, in <module>
    run_gibbs_sampler(
  File "****/hmsc-hpc/hmsc/run_gibbs_sampler.py", line 139, in run_gibbs_sampler
    save_chains_postList_to_rds(postList, postList_file_path, len(chainIndList), elapsedTime, flag_save_eta)
  File "****/hmsc-hpc/hmsc/utils/export_rds_utils.py", line 49, in save_chains_postList_to_rds
    pyreadr.write_rds(postList_file_path, pd.DataFrame([[json_str]]), compress="gzip")
  File "/users//****/./.local/lib/python3.10/site-packages/pyreadr/pyreadr.py", line 206, in write_rds
    writer.write_r(filename_bytes, file_format, df, df_name, dateformat, datetimeformat, compress)
  File "/users/****/.local/lib/python3.10/site-packages/pyreadr/_pyreadr_writer.py", line 230, in write_r
    self.insert_value(row_indx, indx, val, curtype)
  File "pyreadr/librdata.pyx", line 367, in pyreadr.librdata.Writer.insert_value
pyreadr.custom_errors.LibrdataError: Unable to write to file
```
Do you think this can be due to the sudden killing of some jobs earlier than it should be (i.e. do you think using something like `sleep 120` after fitting the models would help)? Is it possible to retrieve information from these temp files?

Thanks

**Comment by pdobbler** [comment]
Hello,

Are there any updates on this issue? We're running into the same error with a larger model. Smaller models run ok.

Thank you!

**Comment by trossi** [comment]
> Are there any updates on this issue? We're running into the same error with a larger model. Smaller models run ok.

The draft PR #2 is expected to resolve this kind of issues, but it is still in the development stage and requires further testing.
